### ISSUE TITLE
extract_receive_messageを追加したら落ちるようになった

### ISSUE THREAD

**Issue by Na0ki** [Na0ki/mikutter_slack#12]
[これ](https://github.com/Na0ki/mikutter_slack/blob/checkExtractMessage/mikutter_slack.rb#L53-L54) を追加したところ、落ちるようになった。  
`extract.rb` の `message.retweet_source` が `method not defined` となる。  
[該当箇所](https://github.com/Na0ki/mikutter_slack/blob/checkExtractMessage/mikutter_slack.rb#L53-L54)  

とりあえずよくわからなかったので、ここに書いた。

ログ

```
/Users/ahiru/mikutter/core/plugin/extract/extract.rb:314:in `block in append_message': undefined method `retweet_source' for "#<Mikutter::System::Message:0x007f96c2a529f8>":String
     from /Users/ahiru/mikutter/core/plugin/extract/extract.rb:314:in `map'
     from /Users/ahiru/mikutter/core/plugin/extract/extract.rb:314:in `append_message'
     from /Users/ahiru/mikutter/core/plugin/extract/extract.rb:207:in `block (2 levels) in <top (required)>'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/listener.rb:25:in `call'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:97:in `block (2 levels) in call_all_listeners'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `each'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `block in call_all_listeners'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `catch'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `call_all_listeners'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:39:in `block in call'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
     from /Users/ahiru/mikutter/core/plugin/gtk/delayer.rb:10:in `block in boot'
     from /Users/ahiru/mikutter/core/plugin/gtk/mainloop.rb:10:in `main'
     from /Users/ahiru/mikutter/core/plugin/gtk/mainloop.rb:10:in `mainloop'
     from mikutter.rb:63:in `boot!'
     from mikutter.rb:92:in `<main>'
notice: mikutter.rb:69:in `rescue in boot!': catch exception `SystemExit'
notice: mikutter.rb:71:in `rescue in boot!': => `SystemExit'
notice: mikutter.rb:96:in `rescue in <main>': catch SystemExit
notice: mikutter.rb:80:in `error_handling!': catch NoMethodError
notice: {MIKUTTER_DIR}/core/configloader.rb:32:in `block in <module:ConfigLoader>': configloader: wrote 2 keys (UserConfig::extract_tabs, UserConfig::ui_tab_order)
/Users/ahiru/mikutter/core/plugin/extract/extract.rb:314:in `map': undefined method `retweet_source' for "#<Mikutter::System::Message:0x007f96c2a529f8>":String (NoMethodError)
    from /Users/ahiru/mikutter/core/plugin/extract/extract.rb:314:in `append_message'
    from /Users/ahiru/mikutter/core/plugin/extract/extract.rb:207:in `block (2 levels) in <top (required)>'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/listener.rb:25:in `call'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:97:in `block (2 levels) in call_all_listeners'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `each'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `block in call_all_listeners'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `catch'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `call_all_listeners'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:39:in `block in call'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
    from /Users/ahiru/mikutter/core/plugin/gtk/delayer.rb:10:in `block in boot'
    from /Users/ahiru/mikutter/core/plugin/gtk/mainloop.rb:10:in `main'
    from /Users/ahiru/mikutter/core/plugin/gtk/mainloop.rb:10:in `mainloop'
    from mikutter.rb:63:in `boot!'
    from mikutter.rb:92:in `<main>'
```

**Comment by toshia** [comment]
システムメッセージは抽出タブでは取り扱うことができない。
Slack用のModelを使ってみよう

**Comment by Na0ki** [comment]
なるほど
ありがとうございます
試してみます

**Comment by Na0ki** [comment]
Model使用時もretweet_sourceで落ちました

```
mikutter_slack: #<Plugin::Slack::Message:0x007ffeb454c850>
/Users/ahiru/mikutter/core/plugin/extract/extract.rb:314:in `block in append_message': undefined method `retweet_source' for "#<Plugin::Slack::Message:0x007ffeb454c850>":String
     from /Users/ahiru/mikutter/core/plugin/extract/extract.rb:314:in `map'
     from /Users/ahiru/mikutter/core/plugin/extract/extract.rb:314:in `append_message'
     from /Users/ahiru/mikutter/core/plugin/extract/extract.rb:207:in `block (2 levels) in <top (required)>'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/listener.rb:25:in `call'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:97:in `block (2 levels) in call_all_listeners'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `each'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `block in call_all_listeners'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `catch'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `call_all_listeners'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:39:in `block in call'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
     from /Users/ahiru/mikutter/core/plugin/gtk/delayer.rb:10:in `block in boot'
     from /Users/ahiru/mikutter/core/plugin/gtk/mainloop.rb:10:in `main'
     from /Users/ahiru/mikutter/core/plugin/gtk/mainloop.rb:10:in `mainloop'
     from mikutter.rb:63:in `boot!'
     from mikutter.rb:92:in `<main>'
notice: mikutter.rb:69:in `rescue in boot!': catch exception `SystemExit'
notice: mikutter.rb:71:in `rescue in boot!': => `SystemExit'
notice: mikutter.rb:96:in `rescue in <main>': catch SystemExit
notice: mikutter.rb:80:in `error_handling!': catch NoMethodError
notice: {MIKUTTER_DIR}/core/configloader.rb:32:in `block in <module:ConfigLoader>': configloader: wrote 3 keys (Plugin::saved_search_last_saved_search_state, UserConfig::extract_tabs, UserConfig::ui_tab_order)
/Users/ahiru/mikutter/core/plugin/extract/extract.rb:314:in `map': undefined method `retweet_source' for "#<Plugin::Slack::Message:0x007ffeb454c850>":String (NoMethodError)
    from /Users/ahiru/mikutter/core/plugin/extract/extract.rb:314:in `append_message'
    from /Users/ahiru/mikutter/core/plugin/extract/extract.rb:207:in `block (2 levels) in <top (required)>'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/listener.rb:25:in `call'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:97:in `block (2 levels) in call_all_listeners'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `each'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `block in call_all_listeners'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `catch'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `call_all_listeners'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:39:in `block in call'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
    from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
    from /Users/ahiru/mikutter/core/plugin/gtk/delayer.rb:10:in `block in boot'
    from /Users/ahiru/mikutter/core/plugin/gtk/mainloop.rb:10:in `main'
    from /Users/ahiru/mikutter/core/plugin/gtk/mainloop.rb:10:in `mainloop'
    from mikutter.rb:63:in `boot!'
    from mikutter.rb:92:in `<main>'
```

**Comment by Na0ki** [comment]
messageを配列に際にうっかり文字列にしてた（てへぺろ）
