### ISSUE TITLE
ヒストリの取得に失敗する

### ISSUE THREAD

**Issue by Na0ki** [Na0ki/mikutter_slack#15]
ヒストリ一覧取得が失敗する
処理追えばいけそうだけど、しばらく手をつけられない。
この辺が怪しそう -> [implHistory](https://github.com/Na0ki/mikutter_slack/blob/implHistory/slack_api.rb#L46-L51)

```
from /Users/ahiru/.mikutter/plugin/mikutter_slack/slack_api.rb:47:in `[]'
from /Users/ahiru/.mikutter/plugin/mikutter_slack/slack_api.rb:47:in `channel_history'
from /Users/ahiru/.mikutter/plugin/mikutter_slack/mikutter_slack.rb:37:in `block (3 levels) in <top (required)>'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:77:in `_execute'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:60:in `block (2 levels) in _call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:59:in `catch'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:59:in `block in _call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:58:in `catch'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:58:in `_call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:25:in `call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:68:in `block (3 levels) in _call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
from {MIKUTTER_DIR}/core/plugin/gtk/delayer.rb:10:in `block in boot'
from {MIKUTTER_DIR}/core/plugin/gtk/mainloop.rb:10:in `main'
from {MIKUTTER_DIR}/core/plugin/gtk/mainloop.rb:10:in `mainloop'
from mikutter.rb:63:in `boot!'
from mikutter.rb:92:in `<main>'
notice: {MIKUTTER_DIR}/core/configloader.rb:32:in `block in <module:ConfigLoader>': configloader: wrote 3 keys (Plugin::saved_search_last_saved_search_state, UserConfig::extract_tabs, UserConfig::ui_tab_order)
```

**Comment by Na0ki** [comment]
コミット [5fd891a](https://github.com/Na0ki/mikutter_slack/commit/5fd891a05c52a077020510de7a6b4abd68d10651) で解決
