### ISSUE TITLE
botの投稿に対応

### ISSUE THREAD

**Issue by Na0ki** [Na0ki/mikutter_slack#28]
botはユーザー一覧で取得できないようなので、現状bot（カスタムインテグレーション）の投稿は以下のエラーにより表示されない

```
warning: {MIKUTTER_DIR}/core/lib/retriever/model.rb:375:in `rescue in block in validate': {:channel=>"mikutter_slack", :user=>nil, :text=>"", :created=>2016-10-07 09:17:19 +0900, :team=>"mikutter"}
error: /Users/ahiru/.mikutter/plugin/slack/slack.rb:53:in `block (4 levels) in <top (required)>': it is required value[nil, User, true]
in nil of user
```

これの影響範囲としては、今の実装だとnilユーザーが来た場合にその先のヒストリの取得が止まってしまうこと

**Comment by Na0ki** [comment]
[これ](https://github.com/Na0ki/mikutter_slack/issues/51)によって得られる情報によって、botの投稿も表示できるようになりそう
