### ISSUE TITLE
複数のデータソースの登録に失敗している

### ISSUE THREAD

**Issue by Na0ki** [Na0ki/mikutter_slack#30]
[implDS](https://github.com/Na0ki/mikutter_slack/blob/implMultiDS/slack.rb#L134-L141) で試しに実装してみたが、うまく動いていない模様。
設定画面の抽出タブの編集を押すと下記エラーを吐いて落ちる

```
/Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/filter.rb:29:in `filtering': undefined method `size' for #<#<Class:0x007fc8d1ebf450>: 70250276342520 stat:nil value:nil>
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:59:in `block (2 levels) in filtering'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:58:in `each'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:58:in `reduce'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:58:in `block in filtering'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:57:in `catch'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:57:in `filtering'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/plugin.rb:63:in `filtering'
     from /Users/ahiru/mikutter/source/core/plugin/extract/edit_window.rb:83:in `source_widget'
     from /Users/ahiru/mikutter/source/core/plugin/extract/edit_window.rb:16:in `initialize'
     from /Users/ahiru/mikutter/source/core/plugin/extract/extract.rb:187:in `new'
     from /Users/ahiru/mikutter/source/core/plugin/extract/extract.rb:187:in `block (2 levels) in <top (required)>'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/listener.rb:25:in `call'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:97:in `block (2 levels) in call_all_listeners'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `each'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:96:in `block in call_all_listeners'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `catch'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:95:in `call_all_listeners'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pluggaloid-1.1.1/lib/pluggaloid/event.rb:39:in `block in call'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
     from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
     from /Users/ahiru/mikutter/source/core/plugin/gtk/delayer.rb:10:in `block in boot'
     from /Users/ahiru/mikutter/source/core/plugin/gtk/mainloop.rb:10:in `main'
     from /Users/ahiru/mikutter/source/core/plugin/gtk/mainloop.rb:10:in `mainloop'
     from mikutter.rb:63:in `boot!'
     from mikutter.rb:92:in `<main>'
notice: mikutter.rb:69:in `rescue in boot!': catch exception `SystemExit'
notice: mikutter.rb:71:in `rescue in boot!': => `SystemExit'
notice: mikutter.rb:96:in `rescue in <main>': catch SystemExit
notice: mikutter.rb:80:in `error_handling!': catch NoMethodError
```

**Comment by Na0ki** [comment]
コミット[ac544bb](https://github.com/Na0ki/mikutter_slack/commit/ac544bb0ef204374c098be8fb8f64cf5198d2f6f)で対応完了
