### ISSUE TITLE
mikutter起動時にチャンネル履歴取得出来ていない？

### ISSUE THREAD

**Issue by whywaita** [Na0ki/mikutter_slack#31]
## 環境
- mikutter_slack ac544bb0ef204374c098be8fb8f64cf5198d2f6f
- mikutter : develop (01a1d0d5b04e26a30c5aede548649d49adfe4614)
- 抽出タブでデータソースにslack指定、現状選択出来る全チャンネルを選択済み
## 現象

mikutter起動時に過去のslackの会話が表示されず、新規のもの(mikutter起動中にslackに投稿されたもの)は表示される
## --debug した時に出てきたそれっぽいログ

```
notice: /Users/whywaita/.mikutter/plugin/slack/slack.rb:24:in `block (3 levels) in <top (required)>':
        ===== 認証成功 =====
        チーム: whywaita
        ユーザー: whywaita
error: /Users/whywaita/.mikutter/plugin/slack/slack.rb:53:in `block (4 levels) in <top (required)>': undefined method `[]' for nil:NilClass
from /Users/whywaita/.mikutter/plugin/slack/api.rb:60:in `block in channel_history'
from {MIKUTTER_DIR}/vendor/bundle/ruby/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/thread.rb:28:in `block (3 levels) in _deferredable_trap_proc'
from {MIKUTTER_DIR}/vendor/bundle/ruby/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/thread.rb:26:in `catch'
from {MIKUTTER_DIR}/vendor/bundle/ruby/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/thread.rb:26:in `block (2 levels) in _deferredable_trap_proc'
from {MIKUTTER_DIR}/vendor/bundle/ruby/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/thread.rb:25:in `catch'
from {MIKUTTER_DIR}/vendor/bundle/ruby/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/thread.rb:25:in `block in _deferredable_trap_proc'
```

**Comment by Na0ki** [comment]
最新の会話にbotが含まれているチャンネルはありますか？
現状botユーザーの取得ができていないため、botユーザの投稿が来るとそれ以降は取得できないです。

**Comment by whywaita** [comment]
なるほど、botユーザーが来るとそこで止まるんですね。
RSSやアラートが頻繁に来ているので、そこで止まっているのかもしれません。

多分大丈夫そうなのでとりあえずクローズします。もしbot以外に要因ありそうならReopenします :bow:

**Comment by Na0ki** [comment]
ログを比べてみたら、わたしの環境でのbotのログとはかなり違うみたいのでreopenさせていただきます。
botが原因の場合はおそらく下記issueのログが吐き出されるはずです。（たぶん）
[#28](https://github.com/Na0ki/mikutter_slack/issues/28)

未知のバグの可能性が高いです。

**Comment by Na0ki** [comment]
6734d91bed0cd3b7a1743e208cee1ee23016756e で対応完了
