### ISSUE TITLE
mikutterを最新のdevelopにしたらプラグインが正常に動かなくなった

### ISSUE THREAD

**Issue by Na0ki** [Na0ki/mikutter_slack#39]
develop: d1871d236540afa40b4b9ba4204d9c5cd468199f
mikutter_slack: e80b232c2ddbf582fb3bb080fbb72f61473e5aa0

下記にログを載せる（個人情報が入っていたので全てhogeに置換）
そのうち追う

```
warning: {MIKUTTER_DIR}/core/lib/retriever/model.rb:378:in `rescue in block in validate': #<Plugin::Slack::User:0x007fb06d565548 @value={:id=>"hoge", :team_id=>"hoge", :name=>"hoge", :deleted=>false, :status=>nil, :color=>"e7392d", :real_name=>"hoge", :tz=>"Asia/Tokyo", :tz_label=>"Japan Standard Time", :tz_offset=>32400, :profile=>{:first_name=>"hoge", :last_name=>"hoge", :avatar_hash=>"g74476e142a7", :real_name=>"Ouchi Akira", :real_name_normalized=>"hoge", :email=>"hoge", :image_24=>"hoge", :image_32=>"hoge", :image_48=>"hoge", :image_72=>"hoge", :image_192=>"hoge", :image_512=>"hoge"}, :is_admin=>false, :is_owner=>false, :is_primary_owner=>false, :is_restricted=>false, :is_ultra_restricted=>false, :is_bot=>false}, @path="/hoge", @_memoized_hash=-3039374064944316451> is not int
from {MIKUTTER_DIR}/core/lib/retriever/model.rb:380:in `rescue in block in validate'
from {MIKUTTER_DIR}/core/lib/retriever/model.rb:374:in `block in validate'
from {MIKUTTER_DIR}/core/lib/retriever/model.rb:372:in `each'
from {MIKUTTER_DIR}/core/lib/retriever/model.rb:372:in `validate'
from {MIKUTTER_DIR}/core/lib/retriever/model.rb:270:in `initialize'
from /Users/ahiru/.mikutter/plugin/slack/api.rb:75:in `new'
from /Users/ahiru/.mikutter/plugin/slack/api.rb:75:in `block (2 levels) in channel_history'
from /Users/ahiru/.mikutter/plugin/slack/api.rb:74:in `map'
from /Users/ahiru/.mikutter/plugin/slack/api.rb:74:in `block in channel_history'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:77:in `_execute'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:60:in `block (2 levels) in _call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:59:in `catch'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:59:in `block in _call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:58:in `catch'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:58:in `_call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:25:in `call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:63:in `block (3 levels) in _call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:77:in `_execute'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:60:in `block (2 levels) in _call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:59:in `catch'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:59:in `block in _call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:58:in `catch'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:58:in `_call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:25:in `call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:84:in `_post'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:14:in `next'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:62:in `block (2 levels) in _call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:59:in `catch'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:59:in `block in _call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:58:in `catch'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:58:in `_call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:25:in `call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:68:in `block (3 levels) in _call'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
from {MIKUTTER_DIR}/core/plugin/gtk/delayer.rb:10:in `block in boot'
from {MIKUTTER_DIR}/core/plugin/gtk/mainloop.rb:10:in `main'
from {MIKUTTER_DIR}/core/plugin/gtk/mainloop.rb:10:in `mainloop'
from {MIKUTTER_DIR}/mikutter.rb:63:in `boot!'
from {MIKUTTER_DIR}/mikutter.rb:92:in `<main>'
```

**Comment by Na0ki** [comment]
この [チケット](http://dev.mikutter.hachune.net/issues/918) に詳細

**Comment by Na0ki** [comment]
```
warning: {MIKUTTER_DIR}/core/lib/retriever/model.rb:378:in `rescue in block in validate': #<Plugin::Slack::User:0x007fc9a2278990 …> is not int
```

```
error: /Users/ahiru/.mikutter/plugin/slack/api/realtime.rb:47:in `block (5 levels) in connected': #<Plugin::Slack::User:0x007fc9a2278990 … > is not int
```

と出ているので、やはりmodelの型周りがおかしいのだろうか

**Comment by Na0ki** [comment]
詳しい報告は後日 [チケット](http://dev.mikutter.hachune.net/issues/918) に報告する
原因としては、 [model/message.rb:](https://github.com/Na0ki/mikutter_slack/blob/master/model/message.rb#L16) の`Plugin::Slack::User` とすべきところを `User` にしていたため、mikutterのトップレベルであるTwitterのUserを参照してしまっていた
