### ISSUE TITLE
png画像が画像ビュアーでひらけない

### ISSUE THREAD

**Issue by Na0ki** [Na0ki/mikutter_slack#40]
外部ブラウザでは正常に見えるが、画像ビュアーで見ようとすると以下のエラーを吐いて落ちる
```
/Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:519:in `invoke': 認識できない画像ファイルの形式
         from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:519:in `block in define_method'
         from /Users/ahiru/mikutter/source/core/plugin/openimg/openimg.rb:53:in `block (4 levels) in <top (required)>'
         from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
         from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
         from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
         from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
         from /Users/ahiru/mikutter/source/core/plugin/gtk/delayer.rb:10:in `block in boot'
         from /Users/ahiru/mikutter/source/core/plugin/gtk/mainloop.rb:10:in `main'
         from /Users/ahiru/mikutter/source/core/plugin/gtk/mainloop.rb:10:in `mainloop'
         from mikutter.rb:65:in `boot!'
         from mikutter.rb:94:in `<main>'

```

**Comment by Na0ki** [comment]
追記
```
/Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:519:in `invoke': 認識できない画像ファイルの形式
	 from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:519:in `block in define_method'
	 from /Users/ahiru/mikutter/source/core/plugin/openimg/openimg.rb:53:in `block (4 levels) in <top (required)>'
	 from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
	 from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
	 from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
	 from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
	 from /Users/ahiru/mikutter/source/core/plugin/gtk/delayer.rb:10:in `block in boot'
	 from /Users/ahiru/mikutter/source/core/plugin/gtk/mainloop.rb:10:in `main'
	 from /Users/ahiru/mikutter/source/core/plugin/gtk/mainloop.rb:10:in `mainloop'
	 from /Users/ahiru/mikutter/source/mikutter.rb:65:in `boot!'
	 from /Users/ahiru/mikutter/source/mikutter.rb:94:in `<main>'
notice: {MIKUTTER_DIR}/mikutter.rb:71:in `rescue in boot!': catch exception `SystemExit'
notice: {MIKUTTER_DIR}/mikutter.rb:73:in `rescue in boot!': => `SystemExit'
notice: {MIKUTTER_DIR}/mikutter.rb:98:in `rescue in <main>': catch SystemExit
notice: {MIKUTTER_DIR}/mikutter.rb:82:in `error_handling!': catch GdkPixbuf::PixbufError::UnknownType
/Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:519:in `block in define_method': 認識できない画像ファイルの形式 (GdkPixbuf::PixbufError::UnknownType)
	from /Users/ahiru/mikutter/source/core/plugin/openimg/openimg.rb:53:in `block (4 levels) in <top (required)>'
	from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
	from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
	from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
	from /Users/ahiru/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
	from /Users/ahiru/mikutter/source/core/plugin/gtk/delayer.rb:10:in `block in boot'
	from /Users/ahiru/mikutter/source/core/plugin/gtk/mainloop.rb:10:in `main'
	from /Users/ahiru/mikutter/source/core/plugin/gtk/mainloop.rb:10:in `mainloop'
	from /Users/ahiru/mikutter/source/mikutter.rb:65:in `boot!'
	from /Users/ahiru/mikutter/source/mikutter.rb:94:in `<main>'
```

**Comment by katsyoshi** [comment]
```
error: /home/katsu/Program/Mikutter/mikutter_slack/api.rb:158:in `block in pingpong': undefined method `>=' for nil:NilClass
from {MIKUTTER_DIR}/.bundle/gems/ruby/2.3.0/gems/faye-websocket-0.9.2/lib/faye/websocket/api.rb:99:in `emit_error'
from {MIKUTTER_DIR}/.bundle/gems/ruby/2.3.0/gems/faye-websocket-0.9.2/lib/faye/websocket/client.rb:56:in `rescue in initialize'
from {MIKUTTER_DIR}/.bundle/gems/ruby/2.3.0/gems/faye-websocket-0.9.2/lib/faye/websocket/client.rb:13:in `initialize'
from /home/katsu/Program/Mikutter/mikutter_slack/api.rb:129:in `new'
from /home/katsu/Program/Mikutter/mikutter_slack/api.rb:129:in `block in pingpong'
from {MIKUTTER_DIR}/.bundle/gems/ruby/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:77:in `_execute'
from {MIKUTTER_DIR}/.bundle/gems/ruby/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:60:in `block (2 levels) in _call'
from {MIKUTTER_DIR}/.bundle/gems/ruby/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:59:in `catch'
from {MIKUTTER_DIR}/.bundle/gems/ruby/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:59:in `block in _call'
from {MIKUTTER_DIR}/.bundle/gems/ruby/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:58:in `catch'
from {MIKUTTER_DIR}/.bundle/gems/ruby/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:58:in `_call'
from {MIKUTTER_DIR}/.bundle/gems/ruby/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:25:in `call'
from {MIKUTTER_DIR}/.bundle/gems/ruby/2.3.0/gems/delayer-deferred-1.0.4/lib/delayer/deferred/deferredable.rb:68:in `block (3 levels) in _call'
from {MIKUTTER_DIR}/.bundle/gems/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
from {MIKUTTER_DIR}/.bundle/gems/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
from {MIKUTTER_DIR}/.bundle/gems/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
from {MIKUTTER_DIR}/.bundle/gems/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
from {MIKUTTER_DIR}/core/plugin/gtk/delayer.rb:10:in `block in boot'
from {MIKUTTER_DIR}/core/plugin/gtk/mainloop.rb:10:in `main'
from {MIKUTTER_DIR}/core/plugin/gtk/mainloop.rb:10:in `mainloop'
from mikutter.rb:66:in `boot!'
from mikutter.rb:95:in `<main>'
(eval):1: warning: constant ::TimeoutError is deprecated
/home/katsu/mikutter/.bundle/gems/ruby/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:519:in `invoke': Unrecognized image file format
         from /home/katsu/mikutter/.bundle/gems/ruby/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:519:in `block in define_method'
         from /home/katsu/mikutter/core/plugin/openimg/openimg.rb:53:in `block (4 levels) in <top (required)>'
         from /home/katsu/mikutter/.bundle/gems/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
         from /home/katsu/mikutter/.bundle/gems/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
         from /home/katsu/mikutter/.bundle/gems/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
         from /home/katsu/mikutter/.bundle/gems/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
         from /home/katsu/mikutter/core/plugin/gtk/delayer.rb:10:in `block in boot'
         from /home/katsu/mikutter/core/plugin/gtk/mainloop.rb:10:in `main'
         from /home/katsu/mikutter/core/plugin/gtk/mainloop.rb:10:in `mainloop'
         from mikutter.rb:66:in `boot!'
         from mikutter.rb:95:in `<main>'
/home/katsu/mikutter/.bundle/gems/ruby/2.3.0/gems/gobject-introspection-3.1.0/lib/gobject-introspection/loader.rb:519:in `block in define_method': Unrecognized image file format (GdkPixbuf::PixbufError::UnknownType)
        from /home/katsu/mikutter/core/plugin/openimg/openimg.rb:53:in `block (4 levels) in <top (required)>'
        from /home/katsu/mikutter/.bundle/gems/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer/procedure.rb:24:in `run'
        from /home/katsu/mikutter/.bundle/gems/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:58:in `run_once'
        from /home/katsu/mikutter/.bundle/gems/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer/extend.rb:30:in `run'
        from /home/katsu/mikutter/.bundle/gems/ruby/2.3.0/gems/delayer-0.0.2/lib/delayer.rb:43:in `method_missing'
        from /home/katsu/mikutter/core/plugin/gtk/delayer.rb:10:in `block in boot'
        from /home/katsu/mikutter/core/plugin/gtk/mainloop.rb:10:in `main'
```
78686ec mikutter以外のチームのヒストリが取得できるように修正

**Comment by Na0ki** [comment]
これは画像を取得しにいった際に、認証が通っていないため認証用HTMLが返ってきて落ちているため落ちている。mikutterは画像を期待しているのにHTMLが返ってきているからである。
画像取得時に `Bearer トークン` を付与すれば取れるようだが、mikutterの `openimg` が先に反応してしまっているよう？なので、現状どう対応すればいいかわからない。

とりあえず、 `get_content()` ではなく `get` でステータスコードを見て処理してみようと思う。

#32 と内容的には同じである。

**Comment by Na0ki** [comment]
プラグイン側だけでは対応しきれないので、mikutterにissueを出す

**Comment by Na0ki** [comment]
#32 と内容は同じなので閉じます
