### ISSUE TITLE
display_requirementを入れていない状態でメッセージの投稿時間を押すと落ちる

### ISSUE THREAD

**Issue by Na0ki** [Na0ki/mikutter_slack#56]
タイトルの通り。
これは詳しく追ってないが、slack_guiの実装が足りていないか、それ以外の要因の可能性もある。
```
/Users/ahiru/mikutter/source/core/plugin/display_requirements/display_requirements.rb:182:in `clicked': undefined method `id' for #<Plugin::Slack::Message:0x007fbd206d24c0>
         from /Users/ahiru/mikutter/source/core/mui/cairo_cell_renderer_message.rb:160:in `block in event_hooks'
         from /Users/ahiru/mikutter/source/core/mui/gtk_extension.rb:33:in `block in safety_signal_connect'
         from /Users/ahiru/mikutter/source/core/mui/cairo_cell_renderer_message.rb:97:in `signal_emit'
         from /Users/ahiru/mikutter/source/core/mui/cairo_cell_renderer_message.rb:97:in `block in tree='
         from /Users/ahiru/mikutter/source/core/mui/gtk_extension.rb:33:in `block in safety_signal_connect'
         from /Users/ahiru/mikutter/source/core/plugin/gtk/mainloop.rb:10:in `main'
         from /Users/ahiru/mikutter/source/core/plugin/gtk/mainloop.rb:10:in `mainloop'
         from /Users/ahiru/mikutter/source/mikutter.rb:66:in `boot!'
         from /Users/ahiru/mikutter/source/mikutter.rb:95:in `<main>'
```

**Comment by rinsuki** [comment]
messageモデルにidの定義が入ってないからじゃないですかね。
とりあえずtsでも返しておけば良さそうな感じがする。
https://github.com/Na0ki/mikutter_slack/blob/master/model/message.rb

**Comment by Na0ki** [comment]
ありがとうございます。
これは完全にTwitterにべったりな感じのが得られましたね。
ひとまずtsを割り当てます。

**Comment by toshia** [comment]
idを要求されるのは恐らくmikutterのバグだと思うんだけど、タイトルにあるメッセージの投稿ってなんですか

**Comment by Na0ki** [comment]
メッセージの投稿…
日本語がおかしかったです。
正しくはメッセージの投稿時間です。

**Comment by rinsuki** [comment]
https://github.com/mikutter/mikutter/blob/master/core/plugin/display_requirements/display_requirements.rb#L181
これかな

**Comment by toshia** [comment]
あーあれか、完全にmikutterのバグなので、mikutter Redmineにごオッラーンくださいますようよろしくお願いします

**Comment by Na0ki** [comment]
了解です。
チケットおっらーんします

**Comment by Na0ki** [comment]
mikutterにおっらーんしたので閉じます
